# -*- coding: utf-8 -*-
"""sales

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fw9B5bT73LOJKuzfZ8GB4mbQDM-lolfs
"""

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("sales.csv")

print(data.head())

print("Shape of data:", data.shape)

print(data.info())

print(data.describe())

sales_by_product = data.groupby("Product")["Sales"].sum()
print(sales_by_product)

sales_by_region = data.groupby("Region")["Sales"].sum()
print(sales_by_region)

sales_by_product.plot(kind="bar", title="Total Sales by Product", figsize=(8,5))
plt.xlabel("Product")
plt.ylabel("Sales")
plt.show()

sales_by_region.plot(kind="pie", autopct='%1.1f%%', figsize=(6,6), title="Sales Distribution by Region")
plt.ylabel("")  # remove y-axis label for pie chart
plt.show()

df["Date"] = pd.to_datetime(df["Date"])

monthly_sales = df.groupby(df["Date"].dt.to_period("M"))["Sales"].sum()

monthly_sales.plot(kind="line", marker="o", title="Monthly Sales Trend", figsize=(8,5))
plt.xlabel("Month")
plt.ylabel("Sales")
plt.show()

"""Conclusion - The analysis shows how sales data can be grouped and visualized to identify trends.
Monthly sales plots help track growth or decline over time, giving useful insights for decision-making.
"""